// @ts-nocheck
// Auto-généré — expose toutes les classes/enums sur globalThis
// pour la compatibilité avec les fichiers @ts-nocheck (pattern global-scripts)

import { enumCouleur, Container, xClass, enumCouleurHexa, enumVisibility, Visibility, enumThemes, enumThemeLuminosite, enumCote, enumStyleBorderCSS, enumCurseur, DictionnaireUtils, Arbre } from './V2/iceBase';
import { ice2Label, enumTypeLabel, enumHabillageLabel, enumMiseEnFormeLabel } from './V2/xcontrols/ice2Label';
import { ice2LabelContainer, enumJustificationDuContenu, enumPositionDuContenu } from './V2/xcontrols/ice2LabelContainer';
import { ice2LabelModifiable } from './V2/xcontrols/ice2LabelModifiable';
import { ice2LabelDateModifiable } from './V2/xcontrols/ice2LabelDateModifiable';
import { ice2LabelTimeModifiable } from './V2/xcontrols/ice2LabelTimeModifiable';
import { ice2Bouton, enumTailleBouton, enumTypeBouton, enumStyleBouton, enumCouleurBouton, enumPositionnementResponsiveBouton, enumComportementBouton } from './V2/xcontrols/ice2Bouton';
import { iceBr } from './V2/xcontrols/iceBr';
import { iceDiv } from './V2/xcontrols/iceDiv';
import { iceSpan } from './V2/xcontrols/iceSpan';
import { iceLString } from './V2/iceLString';
import { ObservableCollection } from './V2/xcontrols/ObservableCollection';
import { IconeP12, IconeSvg, IconeTuile, enumIconeP12, enumIconeSvg, enumIconeTuile, enumIconeZeusSvg, tailleIcone, enumIconeAction, IconeV2, IconeMiniP12, IconeExterne, IconeTypeExamen, enumListeIcones, enumFormeFondIconeSvg } from './V2/iceIcones';
import { xInputText, enumStyleInput, enumBackgroundInput } from './V2/xcontrols/iceInput';
import { iceInputDate, xInputTime, xInputDateAndTime, enumTypeAffichePicker } from './V2/xcontrols/iceInputDate';
import { iceDatePicker } from './V2/xcontrols/iceDatePicker';
import { iceTimePicker } from './V2/xcontrols/iceTimePicker';
import { iceCanvas } from './V2/xcontrols/iceCanvas';
import { iceCouleur } from './V2/xcontrols/iceCouleur';
import { iceHref, enumTypeOuvertureHref } from './V2/xcontrols/iceHref';
import { iceIFrame } from './V2/xcontrols/iceIFrame';
import { iceImg } from './V2/xcontrols/iceImg';
import { iceInputCheckBox } from './V2/xcontrols/iceInputCheckBox';
import { iceInputFile } from './V2/xcontrols/iceInputFile';
import { iceLi } from './V2/xcontrols/iceLi';
import { iceSeparateur, enumEpaisseurSeparation } from './V2/xcontrols/iceSeparateur';
import { iceTable } from './V2/xcontrols/iceTable';
import { iceUl } from './V2/xcontrols/iceUl';
import { iceInputTextAvecIcone } from './V2/xcontrols/iceInputTextAvecIcone';
import { ice2Arbre } from './V2/xcontrols/ice2Arbre';
import { ice2AssistantSaisieUtilisateur } from './V2/xcontrols/ice2AssistantSaisieUser';
import { ice2AutoComplete, enumAutoCompleteTaille } from './V2/xcontrols/ice2AutoComplete';
import { ice2BloqueEcran } from './V2/xcontrols/ice2BloqueEcran';
import { ice2Boxer, enumBoxerMode, enumBoxerTaille, enumPositionOrigine } from './V2/xcontrols/ice2Boxer';
import { ice2Carrousel } from './V2/xcontrols/ice2Carrousel';
import { ice2CheckBox, enumTypeCheckbox } from './V2/xcontrols/ice2CheckBox';
import { ice2ChoixCouleur, enumNuancierCouleurs } from './V2/xcontrols/ice2ChoixCouleur';
import { ice2ChoixOuiNon } from './V2/xcontrols/ice2ChoixOuiNon';
import { ice2ContainerEvent } from './V2/xcontrols/ice2ContainerEvent';
import { ice2Dialog, enumDialogTypeBouton, enumTypeAlerte } from './V2/xcontrols/ice2Dialog';
import { ice2DockPanelDeprecated, DockPosition } from './V2/xcontrols/ice2DockPanel';
import { ice2Grid, ice2GridItem, enumAlignementContenu } from './V2/xcontrols/ice2Grid';
import { ice2ImageTabByte, enumTypeImage } from './V2/xcontrols/ice2ImageTabByte';
import { ice2InputIntellisense } from './V2/xcontrols/ice2InputIntellisense';
import { ice2InputNumerique } from './V2/xcontrols/ice2InputNumerique';
import { ice2InputSpeech } from './V2/xcontrols/ice2InputSpeech';
import { ice2InputUploadImage } from './V2/xcontrols/ice2InputUploadImage';
import { ice2LecteurCarteMagnetique } from './V2/xcontrols/ice2LecteurCarteMagnetique';
import { ice2Linker } from './V2/xcontrols/ice2Linker';
import { ice2ListCheckBox } from './V2/xcontrols/ice2ListCheckBox';
import { ice2ListChoix } from './V2/xcontrols/ice2ListChoix';
import { ice2ListWrapper, enumTypeTri } from './V2/xcontrols/ice2ListWrapper';
import { ice2ListeDeroulante } from './V2/xcontrols/ice2ListeDeroulante';
import { ice2ListeDeroulanteAutomatique } from './V2/xcontrols/ice2ListeDeroulanteAutomatique';
import { ice2ListeDeroulanteSimpleNePlusUtiliser } from './V2/xcontrols/ice2ListeDeroulanteSimple';
import { ice2ListeSelection } from './V2/xcontrols/ice2ListeSelection';
import { ice2ListeChoixLang } from './V2/xcontrols/ice2ListChoixLang';
import { ice2Menu } from './V2/xcontrols/ice2Menu';
import { ice2NavOngletControl, ice2NavOngletItem } from './V2/xcontrols/ice2NavOngletControl';
import { ice2PageWrapper, enumAlignementZone } from './V2/xcontrols/ice2PageWrapper';
import { ice2Planneur, PlanneurRessource, PlanneurRDV, ice2PlanneurColonne, ice2PlanneurLigne } from './V2/xcontrols/ice2Planneur';
import { ice2ProgressBar } from './V2/xcontrols/ice2ProgressBar';
import { ice2QrCodeReader } from './V2/xcontrols/ice2QrCodeReader';
import { ice2RadioButton, ETypeBouton, itemRadioButton } from './V2/xcontrols/ice2RadioButton';
import { ice2RouteContainer } from './V2/xcontrols/ice2RouteContainer';
import { ice2StackPanel } from './V2/xcontrols/ice2StackPanel';
import { ice2TabControl, ice2TabItem } from './V2/xcontrols/ice2TabControl';
import { ice2TableauWrapper } from './V2/xcontrols/ice2Tableau';
import { ice2TexteEnrichi } from './V2/xcontrols/ice2TexteEnrichi';
import { ice2ToolTip, ice2ToolTipBouton, enumXxToolTipMode, enumXxToolTipPositionHeight, enumXxToolTipPositionWidth } from './V2/xcontrols/ice2ToolTip';
import { ice2TreeTabControl } from './V2/xcontrols/ice2TreeTabControl';
import { ice2ViewerPDF } from './V2/xcontrols/ice2ViewerPDF';
import { ice2Volet, enumPositionVolet } from './V2/xcontrols/ice2Volet';
import { ice2WrapPanel, enumAlignementVerticalWrapPanel, enumAlignementHorizontalWrapPanel } from './V2/xcontrols/ice2WrapPanel';
import { ice2ZoneModulable, EEtatZoneModulable } from './V2/xcontrols/ice2ZoneModulable';
import { ice2ZoneRepliable, enumXxZoneRepliableCouleurFleche, enumXxZoneRepliablePosition } from './V2/xcontrols/ice2ZoneRepliable';
import { ice2Zoom, enumAffichageZoom } from './V2/xcontrols/ice2Zoom';
import { enumTypeOrientation, enumPosition } from './V2/iceBase';
import { ice2Planning, EPlanningTypeAffichage } from './V2/Planning/ice2Planning';
import { PlanningRdv, PlanningDisponibilite, PlanningRessource, enumTypeDispo } from './V2/Planning/PlanningElements';
import { cachericeElements, affichericeElements, videriceElements, assignerObjet } from './iceStaticFunctions';
import { DateSerialisable } from './V2/utils/DateSerialisableExtend';
import { HelperGeneric } from './V2/utils/HelperGeneric';
import { iceOutils, EKeys, ETypeAlertify, EnumLibrairieJs } from './iceOutils';
import { xElementHolder } from './iceElement';
import { iceMaths } from './V2/iceMaths';
import { iceTime } from './V2/iceTime';
import { BindableObject } from './V2/xcontrols/BindableObject';
import { iceStyle } from './V2/xcontrols/iceStyle';
import { iceSVG } from './V2/xcontrols/iceSVG';
import { mChart } from './V2/xcontrols/ice2Chart';

// Assignments directs — exécutés au chargement du module
(globalThis as any).mChart = mChart;
(globalThis as any).iceSVG = iceSVG;
(globalThis as any).EnumLibrairieJs = EnumLibrairieJs;
(globalThis as any).enumCouleur = enumCouleur;
(globalThis as any).xClass = xClass;
(globalThis as any).enumCouleurHexa = enumCouleurHexa;
(globalThis as any).enumVisibility = enumVisibility;
(globalThis as any).Visibility = Visibility;
(globalThis as any).enumThemes = enumThemes;
(globalThis as any).enumThemeLuminosite = enumThemeLuminosite;
(globalThis as any).enumCote = enumCote;
(globalThis as any).enumStyleBorderCSS = enumStyleBorderCSS;
(globalThis as any).enumCurseur = enumCurseur;
(globalThis as any).DictionnaireUtils = DictionnaireUtils;
(globalThis as any).Arbre = Arbre;
(globalThis as any).ice2Label = ice2Label;
(globalThis as any).enumTypeLabel = enumTypeLabel;
(globalThis as any).enumHabillageLabel = enumHabillageLabel;
(globalThis as any).enumMiseEnFormeLabel = enumMiseEnFormeLabel;
(globalThis as any).ice2LabelContainer = ice2LabelContainer;
(globalThis as any).enumJustificationDuContenu = enumJustificationDuContenu;
(globalThis as any).enumPositionDuContenu = enumPositionDuContenu;
(globalThis as any).ice2LabelModifiable = ice2LabelModifiable;
(globalThis as any).ice2LabelDateModifiable = ice2LabelDateModifiable;
(globalThis as any).ice2LabelTimeModifiable = ice2LabelTimeModifiable;
(globalThis as any).ice2Bouton = ice2Bouton;
(globalThis as any).enumTailleBouton = enumTailleBouton;
(globalThis as any).enumTypeBouton = enumTypeBouton;
(globalThis as any).enumStyleBouton = enumStyleBouton;
(globalThis as any).enumCouleurBouton = enumCouleurBouton;
(globalThis as any).enumPositionnementResponsiveBouton = enumPositionnementResponsiveBouton;
(globalThis as any).iceBr = iceBr;
(globalThis as any).iceDiv = iceDiv;
(globalThis as any).iceSpan = iceSpan;
(globalThis as any).iceLString = iceLString;
(globalThis as any).ObservableCollection = ObservableCollection;
(globalThis as any).IconeP12 = IconeP12;
(globalThis as any).IconeSvg = IconeSvg;
(globalThis as any).IconeTuile = IconeTuile;
(globalThis as any).enumIconeP12 = enumIconeP12;
(globalThis as any).enumIconeSvg = enumIconeSvg;
(globalThis as any).enumIconeTuile = enumIconeTuile;
(globalThis as any).enumIconeZeusSvg = enumIconeZeusSvg;
(globalThis as any).tailleIcone = tailleIcone;
(globalThis as any).enumIconeAction = enumIconeAction;
(globalThis as any).IconeV2 = IconeV2;
(globalThis as any).IconeMiniP12 = IconeMiniP12;
(globalThis as any).IconeExterne = IconeExterne;
(globalThis as any).IconeTypeExamen = IconeTypeExamen;
(globalThis as any).enumListeIcones = enumListeIcones;
(globalThis as any).enumFormeFondIconeSvg = enumFormeFondIconeSvg;
(globalThis as any).xInputText = xInputText;
(globalThis as any).enumStyleInput = enumStyleInput;
(globalThis as any).enumBackgroundInput = enumBackgroundInput;
(globalThis as any).iceInputDate = iceInputDate;
(globalThis as any).xInputTime = xInputTime;
(globalThis as any).xInputDateAndTime = xInputDateAndTime;
(globalThis as any).enumTypeAffichePicker = enumTypeAffichePicker;
(globalThis as any).iceDatePicker = iceDatePicker;
(globalThis as any).iceTimePicker = iceTimePicker;
(globalThis as any).iceCanvas = iceCanvas;
(globalThis as any).iceCouleur = iceCouleur;
(globalThis as any).iceHref = iceHref;
(globalThis as any).enumTypeOuvertureHref = enumTypeOuvertureHref;
(globalThis as any).iceIFrame = iceIFrame;
(globalThis as any).iceImg = iceImg;
(globalThis as any).iceInputCheckBox = iceInputCheckBox;
(globalThis as any).iceInputFile = iceInputFile;
(globalThis as any).iceLi = iceLi;
(globalThis as any).iceSeparateur = iceSeparateur;
(globalThis as any).enumEpaisseurSeparation = enumEpaisseurSeparation;
(globalThis as any).iceTable = iceTable;
(globalThis as any).iceUl = iceUl;
(globalThis as any).iceInputTextAvecIcone = iceInputTextAvecIcone;
(globalThis as any).ice2Arbre = ice2Arbre;
(globalThis as any).ice2AssistantSaisieUtilisateur = ice2AssistantSaisieUtilisateur;
(globalThis as any).ice2AutoComplete = ice2AutoComplete;
(globalThis as any).enumAutoCompleteTaille = enumAutoCompleteTaille;
(globalThis as any).ice2BloqueEcran = ice2BloqueEcran;
(globalThis as any).ice2Boxer = ice2Boxer;
(globalThis as any).enumBoxerMode = enumBoxerMode;
(globalThis as any).enumBoxerTaille = enumBoxerTaille;
(globalThis as any).enumPositionOrigine = enumPositionOrigine;
(globalThis as any).ice2Carrousel = ice2Carrousel;
(globalThis as any).ice2CheckBox = ice2CheckBox;
(globalThis as any).enumTypeCheckbox = enumTypeCheckbox;
(globalThis as any).ice2ChoixCouleur = ice2ChoixCouleur;
(globalThis as any).enumNuancierCouleurs = enumNuancierCouleurs;
(globalThis as any).ice2ChoixOuiNon = ice2ChoixOuiNon;
(globalThis as any).ice2ContainerEvent = ice2ContainerEvent;
(globalThis as any).ice2Dialog = ice2Dialog;
(globalThis as any).enumDialogTypeBouton = enumDialogTypeBouton;
(globalThis as any).enumTypeAlerte = enumTypeAlerte;
(globalThis as any).ice2DockPanelDeprecated = ice2DockPanelDeprecated;
(globalThis as any).DockPosition = DockPosition;
(globalThis as any).ice2Grid = ice2Grid;
(globalThis as any).ice2GridItem = ice2GridItem;
(globalThis as any).enumAlignementContenu = enumAlignementContenu;
(globalThis as any).ice2ImageTabByte = ice2ImageTabByte;
(globalThis as any).enumTypeImage = enumTypeImage;
(globalThis as any).ice2InputIntellisense = ice2InputIntellisense;
(globalThis as any).ice2InputNumerique = ice2InputNumerique;
(globalThis as any).ice2InputSpeech = ice2InputSpeech;
(globalThis as any).ice2InputUploadImage = ice2InputUploadImage;
(globalThis as any).ice2LecteurCarteMagnetique = ice2LecteurCarteMagnetique;
(globalThis as any).ice2Linker = ice2Linker;
(globalThis as any).ice2ListCheckBox = ice2ListCheckBox;
(globalThis as any).ice2ListChoix = ice2ListChoix;
(globalThis as any).ice2ListWrapper = ice2ListWrapper;
(globalThis as any).enumTypeTri = enumTypeTri;
(globalThis as any).ice2ListeDeroulante = ice2ListeDeroulante;
(globalThis as any).ice2ListeDeroulanteAutomatique = ice2ListeDeroulanteAutomatique;
(globalThis as any).ice2ListeDeroulanteSimpleNePlusUtiliser = ice2ListeDeroulanteSimpleNePlusUtiliser;
(globalThis as any).ice2ListeSelection = ice2ListeSelection;
(globalThis as any).ice2ListeChoixLang = ice2ListeChoixLang;
(globalThis as any).ice2Menu = ice2Menu;
(globalThis as any).ice2NavOngletControl = ice2NavOngletControl;
(globalThis as any).ice2NavOngletItem = ice2NavOngletItem;
(globalThis as any).ice2PageWrapper = ice2PageWrapper;
(globalThis as any).enumAlignementZone = enumAlignementZone;
(globalThis as any).ice2Planneur = ice2Planneur;
(globalThis as any).PlanneurRessource = PlanneurRessource;
(globalThis as any).PlanneurRDV = PlanneurRDV;
(globalThis as any).ice2PlanneurColonne = ice2PlanneurColonne;
(globalThis as any).ice2PlanneurLigne = ice2PlanneurLigne;
(globalThis as any).ice2ProgressBar = ice2ProgressBar;
(globalThis as any).ice2QrCodeReader = ice2QrCodeReader;
(globalThis as any).ice2RadioButton = ice2RadioButton;
(globalThis as any).itemRadioButton = itemRadioButton;
(globalThis as any).ETypeBouton = ETypeBouton;
(globalThis as any).ice2RouteContainer = ice2RouteContainer;
(globalThis as any).ice2StackPanel = ice2StackPanel;
(globalThis as any).ice2TabControl = ice2TabControl;
(globalThis as any).ice2TabItem = ice2TabItem;
(globalThis as any).ice2TableauWrapper = ice2TableauWrapper;
(globalThis as any).ice2TexteEnrichi = ice2TexteEnrichi;
(globalThis as any).ice2ToolTip = ice2ToolTip;
(globalThis as any).enumXxToolTipMode = enumXxToolTipMode;
(globalThis as any).enumXxToolTipPositionHeight = enumXxToolTipPositionHeight;
(globalThis as any).enumXxToolTipPositionWidth = enumXxToolTipPositionWidth;
(globalThis as any).ice2TreeTabControl = ice2TreeTabControl;
(globalThis as any).ice2ViewerPDF = ice2ViewerPDF;
(globalThis as any).ice2Volet = ice2Volet;
(globalThis as any).enumPositionVolet = enumPositionVolet;
(globalThis as any).ice2WrapPanel = ice2WrapPanel;
(globalThis as any).enumAlignementVerticalWrapPanel = enumAlignementVerticalWrapPanel;
(globalThis as any).enumAlignementHorizontalWrapPanel = enumAlignementHorizontalWrapPanel;
(globalThis as any).ice2ZoneModulable = ice2ZoneModulable;
(globalThis as any).EEtatZoneModulable = EEtatZoneModulable;
(globalThis as any).ice2ZoneRepliable = ice2ZoneRepliable;
(globalThis as any).enumXxZoneRepliableCouleurFleche = enumXxZoneRepliableCouleurFleche;
(globalThis as any).enumXxZoneRepliablePosition = enumXxZoneRepliablePosition;
(globalThis as any).ice2Zoom = ice2Zoom;
(globalThis as any).enumAffichageZoom = enumAffichageZoom;
(globalThis as any).enumTypeOrientation = enumTypeOrientation;
(globalThis as any).enumPosition = enumPosition;
(globalThis as any).ice2Planning = ice2Planning;
(globalThis as any).EPlanningTypeAffichage = EPlanningTypeAffichage;
(globalThis as any).PlanningRdv = PlanningRdv;
(globalThis as any).PlanningDisponibilite = PlanningDisponibilite;
(globalThis as any).enumTypeDispo = enumTypeDispo;
(globalThis as any).cachericeElements = cachericeElements;
(globalThis as any).affichericeElements = affichericeElements;
(globalThis as any).videriceElements = videriceElements;
(globalThis as any).assignerObjet = assignerObjet;
(globalThis as any).DateSerialisable = DateSerialisable;
(globalThis as any).HelperGeneric = HelperGeneric;
(globalThis as any).iceOutils = iceOutils;
(globalThis as any).EKeys = EKeys;
(globalThis as any).ETypeAlertify = ETypeAlertify;
(globalThis as any).xElementHolder = xElementHolder;
(globalThis as any).iceMaths = iceMaths;
(globalThis as any).iceTime = iceTime;
(globalThis as any).BindableObject = BindableObject;
(globalThis as any).iceStyle = iceStyle;
(globalThis as any).Container = Container;
(globalThis as any).enumComportementBouton = enumComportementBouton;
(globalThis as any).ice2ToolTipBouton = ice2ToolTipBouton;
(globalThis as any).PlanningRdv = PlanningRdv;
(globalThis as any).PlanningDisponibilite = PlanningDisponibilite;
(globalThis as any).PlanningRessource = PlanningRessource;
(globalThis as any).enumTypeDispo = enumTypeDispo;
