// @ts-nocheck
// Auto-généré — expose toutes les classes/enums sur globalThis
// pour la compatibilité avec les fichiers @ts-nocheck (pattern global-scripts)

import { xxShowRoomContainer, ExxShowRoomContainerTypeOption, ExxShowRoomContaineGoupeElement, ExxShowRoomContaineDataType } from './V2/xcontrols/showroom/xxShowRoomContainer';
import { enumCouleur, Container, xClass, enumCouleurHexa, enumVisibility, Visibility, enumThemes, enumThemeLuminosite, enumCote, enumStyleBorderCSS, enumCurseur, DictionnaireUtils, Arbre } from './V2/xBase';
import { xxLabel, enumTypeLabel, enumHabillageLabel, enumMiseEnFormeLabel } from './V2/xcontrols/xxLabel';
import { xxLabelContainer, enumJustificationDuContenu, enumPositionDuContenu } from './V2/xcontrols/xxLabelContainer';
import { xxLabelModifiable } from './V2/xcontrols/xxLabelModifiable';
import { xxLabelDateModifiable } from './V2/xcontrols/xxLabelDateModifiable';
import { xxLabelTimeModifiable } from './V2/xcontrols/xxLabelTimeModifiable';
import { xxBouton, enumTailleBouton, enumTypeBouton, enumStyleBouton, enumCouleurBouton, enumPositionnementResponsiveBouton, enumComportementBouton } from './V2/xcontrols/xxBouton';
import { xBr } from './V2/xcontrols/xBr';
import { xDiv } from './V2/xcontrols/xDiv';
import { xSpan } from './V2/xcontrols/xSpan';
import { xLString } from './V2/xLString';
import { xxShowRoomSample } from './V2/xcontrols/showroom/xxShowRoomSample';
import { xxShowRoomImageTooltipPreview } from './V2/xcontrols/showroom/xxShowRoomImageTooltipPreview';
import { xxShowRoomOptionRecurrente } from './V2/xcontrols/showroom/xxShowRoomOptionRecurrente';
import { ObservableCollection } from './V2/xcontrols/ObservableCollection';
import { IconeP12, IconeSvg, IconeTuile, enumIconeP12, enumIconeSvg, enumIconeTuile, enumIconeEmedSvg, tailleIcone, enumIconeAction, IconeV2, IconeMiniP12, IconeExterne, IconeTypeExamen, enumListeIcones, enumFormeFondIconeSvg } from './V2/xIcones';
import { xInputText, enumStyleInput, enumBackgroundInput } from './V2/xcontrols/xInput';
import { xInputDate, xInputTime, xInputDateAndTime, enumTypeAffichePicker } from './V2/xcontrols/xInputDate';
import { xDatePicker } from './V2/xcontrols/xDatePicker';
import { xTimePicker } from './V2/xcontrols/xTimePicker';
import { xCanvas } from './V2/xcontrols/xCanvas';
import { xCouleur } from './V2/xcontrols/xCouleur';
import { xHref, enumTypeOuvertureHref } from './V2/xcontrols/xHref';
import { xIFrame } from './V2/xcontrols/xIFrame';
import { xImg } from './V2/xcontrols/xImg';
import { xInputCheckBox } from './V2/xcontrols/xInputCheckBox';
import { xInputFile } from './V2/xcontrols/xInputFile';
import { xLi } from './V2/xcontrols/xLi';
import { xSeparateur, enumEpaisseurSeparation } from './V2/xcontrols/xSeparateur';
import { xTable } from './V2/xcontrols/xTable';
import { xUl } from './V2/xcontrols/xUl';
import { xInputTextAvecIcone } from './V2/xcontrols/xInputTextAvecIcone';
import { xxArbre } from './V2/xcontrols/xxArbre';
import { xxAssistantSaisieUtilisateur } from './V2/xcontrols/xxAssistantSaisieUser';
import { xxAutoComplete, enumAutoCompleteTaille } from './V2/xcontrols/xxAutoComplete';
import { xxBloqueEcran } from './V2/xcontrols/xxBloqueEcran';
import { xxBoxer, enumBoxerMode, enumBoxerTaille, enumPositionOrigine } from './V2/xcontrols/xxBoxer';
import { xxCarrousel } from './V2/xcontrols/xxCarrousel';
import { xxCheckBox, enumTypeCheckbox } from './V2/xcontrols/xxCheckBox';
import { xxChoixCouleur, enumNuancierCouleurs } from './V2/xcontrols/xxChoixCouleur';
import { xxChoixOuiNon } from './V2/xcontrols/xxChoixOuiNon';
import { xxContainerEvent } from './V2/xcontrols/xxContainerEvent';
import { xxDialog, enumDialogTypeBouton, enumTypeAlerte } from './V2/xcontrols/xxDialog';
import { xxDockPanelDeprecated, DockPosition } from './V2/xcontrols/xxDockPanel';
import { xxGrid, xxGridItem, enumAlignementContenu } from './V2/xcontrols/xxGrid';
import { xxIMC } from './V2/xcontrols/xxIMC';
import { xxImageTabByte, enumTypeImage } from './V2/xcontrols/xxImageTabByte';
import { xxIndicateur, EnumXxIndicateurNotifColor } from './V2/xcontrols/xxIndicateur';
import { xxInputIntellisense } from './V2/xcontrols/xxInputIntellisense';
import { xxInputNumerique } from './V2/xcontrols/xxInputNumerique';
import { xxInputSpeech } from './V2/xcontrols/xxInputSpeech';
import { xxInputUploadImage } from './V2/xcontrols/xxInputUploadImage';
import { xxLecteurAudio } from './V2/xcontrols/xxLecteurAudio';
import { xxLecteurCarteMagnetique } from './V2/xcontrols/xxLecteurCarteMagnetique';
import { xxLinker } from './V2/xcontrols/xxLinker';
import { xxListCheckBox } from './V2/xcontrols/xxListCheckBox';
import { xxListChoix } from './V2/xcontrols/xxListChoix';
import { xxListWrapper, enumTypeTri } from './V2/xcontrols/xxListWrapper';
import { xxListeDeroulante } from './V2/xcontrols/xxListeDeroulante';
import { xxListeDeroulanteAutomatique } from './V2/xcontrols/xxListeDeroulanteAutomatique';
import { xxListeDeroulanteSimpleNePlusUtiliser } from './V2/xcontrols/xxListeDeroulanteSimple';
import { xxListeSelection } from './V2/xcontrols/xxListeSelection';
import { xxListeChoixLang } from './V2/xcontrols/xxListChoixLang';
import { xxMenu } from './V2/xcontrols/xxMenu';
import { xxNavOngletControl, xxNavOngletItem } from './V2/xcontrols/xxNavOngletControl';
import { xxPageWrapper, enumAlignementZone } from './V2/xcontrols/xxPageWrapper';
import { xxPlanneur, PlanneurRessource, PlanneurRDV, xxPlanneurColonne, xxPlanneurLigne } from './V2/xcontrols/xxPlanneur';
import { xxProgressBar } from './V2/xcontrols/xxProgressBar';
import { xxQrCodeReader } from './V2/xcontrols/xxQrCodeReader';
import { xxRadioButton, ETypeBouton, itemRadioButton } from './V2/xcontrols/xxRadioButton';
import { xxRecorder } from './V2/xcontrols/xxRecorder';
import { xxRouteContainer } from './V2/xcontrols/xxRouteContainer';
import { xxSpecificationCreneaux } from './V2/xcontrols/xxSpecificationCreneaux';
import { xxStackPanel } from './V2/xcontrols/xxStackPanel';
import { xxTabControl, xxTabItem } from './V2/xcontrols/xxTabControl';
import { xxTableauWrapper } from './V2/xcontrols/xxTableau';
import { xxTexteEnrichi } from './V2/xcontrols/xxTexteEnrichi';
import { xxToolTip, xxToolTipBouton, enumXxToolTipMode, enumXxToolTipPositionHeight, enumXxToolTipPositionWidth } from './V2/xcontrols/xxToolTip';
import { xxTreeTabControl } from './V2/xcontrols/xxTreeTabControl';
import { xxViewerPDF } from './V2/xcontrols/xxViewerPDF';
import { xxVolet, enumPositionVolet } from './V2/xcontrols/xxVolet';
import { xxWrapPanel, enumAlignementVerticalWrapPanel, enumAlignementHorizontalWrapPanel } from './V2/xcontrols/xxWrapPanel';
import { xxZoneModulable, EEtatZoneModulable } from './V2/xcontrols/xxZoneModulable';
import { xxZoneRepliable, enumXxZoneRepliableCouleurFleche, enumXxZoneRepliablePosition } from './V2/xcontrols/xxZoneRepliable';
import { xxZoom, enumAffichageZoom } from './V2/xcontrols/xxZoom';
import { enumTypeOrientation, enumPosition } from './V2/xBase';
import { xxPlanning, EPlanningTypeAffichage } from './V2/Planning/xxPlanning';
import { PlanningRdv, PlanningDisponibilite, PlanningRessource, enumTypeDispo } from './V2/Planning/PlanningElements';
import { cacherxElements, afficherxElements, viderxElements, assignerObjet } from './xStaticFunctions';
import { DateSerialisable } from './V2/utils/DateSerialisableExtend';
import { HelperGeneric } from './V2/utils/HelperGeneric';
import { xOutils, EKeys, ETypeAlertify } from './xOutils';
import { xElementHolder } from './xElement';
import { xMaths } from './V2/xMaths';
import { xTime } from './V2/xTime';
import { BindableObject } from './V2/xcontrols/BindableObject';
import { xStyle } from './V2/xcontrols/xStyle';

// Assignments directs — exécutés au chargement du module
(globalThis as any).xxShowRoomContainer = xxShowRoomContainer;
(globalThis as any).ExxShowRoomContainerTypeOption = ExxShowRoomContainerTypeOption;
(globalThis as any).ExxShowRoomContaineGoupeElement = ExxShowRoomContaineGoupeElement;
(globalThis as any).ExxShowRoomContaineDataType = ExxShowRoomContaineDataType;
(globalThis as any).enumCouleur = enumCouleur;
(globalThis as any).xClass = xClass;
(globalThis as any).enumCouleurHexa = enumCouleurHexa;
(globalThis as any).enumVisibility = enumVisibility;
(globalThis as any).Visibility = Visibility;
(globalThis as any).enumThemes = enumThemes;
(globalThis as any).enumThemeLuminosite = enumThemeLuminosite;
(globalThis as any).enumCote = enumCote;
(globalThis as any).enumStyleBorderCSS = enumStyleBorderCSS;
(globalThis as any).enumCurseur = enumCurseur;
(globalThis as any).DictionnaireUtils = DictionnaireUtils;
(globalThis as any).Arbre = Arbre;
(globalThis as any).xxLabel = xxLabel;
(globalThis as any).enumTypeLabel = enumTypeLabel;
(globalThis as any).enumHabillageLabel = enumHabillageLabel;
(globalThis as any).enumMiseEnFormeLabel = enumMiseEnFormeLabel;
(globalThis as any).xxLabelContainer = xxLabelContainer;
(globalThis as any).enumJustificationDuContenu = enumJustificationDuContenu;
(globalThis as any).enumPositionDuContenu = enumPositionDuContenu;
(globalThis as any).xxLabelModifiable = xxLabelModifiable;
(globalThis as any).xxLabelDateModifiable = xxLabelDateModifiable;
(globalThis as any).xxLabelTimeModifiable = xxLabelTimeModifiable;
(globalThis as any).xxBouton = xxBouton;
(globalThis as any).enumTailleBouton = enumTailleBouton;
(globalThis as any).enumTypeBouton = enumTypeBouton;
(globalThis as any).enumStyleBouton = enumStyleBouton;
(globalThis as any).enumCouleurBouton = enumCouleurBouton;
(globalThis as any).enumPositionnementResponsiveBouton = enumPositionnementResponsiveBouton;
(globalThis as any).xBr = xBr;
(globalThis as any).xDiv = xDiv;
(globalThis as any).xSpan = xSpan;
(globalThis as any).xLString = xLString;
(globalThis as any).xxShowRoomSample = xxShowRoomSample;
(globalThis as any).xxShowRoomImageTooltipPreview = xxShowRoomImageTooltipPreview;
(globalThis as any).xxShowRoomOptionRecurrente = xxShowRoomOptionRecurrente;
(globalThis as any).ObservableCollection = ObservableCollection;
(globalThis as any).IconeP12 = IconeP12;
(globalThis as any).IconeSvg = IconeSvg;
(globalThis as any).IconeTuile = IconeTuile;
(globalThis as any).enumIconeP12 = enumIconeP12;
(globalThis as any).enumIconeSvg = enumIconeSvg;
(globalThis as any).enumIconeTuile = enumIconeTuile;
(globalThis as any).enumIconeEmedSvg = enumIconeEmedSvg;
(globalThis as any).tailleIcone = tailleIcone;
(globalThis as any).enumIconeAction = enumIconeAction;
(globalThis as any).IconeV2 = IconeV2;
(globalThis as any).IconeMiniP12 = IconeMiniP12;
(globalThis as any).IconeExterne = IconeExterne;
(globalThis as any).IconeTypeExamen = IconeTypeExamen;
(globalThis as any).enumListeIcones = enumListeIcones;
(globalThis as any).enumFormeFondIconeSvg = enumFormeFondIconeSvg;
(globalThis as any).xInputText = xInputText;
(globalThis as any).enumStyleInput = enumStyleInput;
(globalThis as any).enumBackgroundInput = enumBackgroundInput;
(globalThis as any).xInputDate = xInputDate;
(globalThis as any).xInputTime = xInputTime;
(globalThis as any).xInputDateAndTime = xInputDateAndTime;
(globalThis as any).enumTypeAffichePicker = enumTypeAffichePicker;
(globalThis as any).xDatePicker = xDatePicker;
(globalThis as any).xTimePicker = xTimePicker;
(globalThis as any).xCanvas = xCanvas;
(globalThis as any).xCouleur = xCouleur;
(globalThis as any).xHref = xHref;
(globalThis as any).enumTypeOuvertureHref = enumTypeOuvertureHref;
(globalThis as any).xIFrame = xIFrame;
(globalThis as any).xImg = xImg;
(globalThis as any).xInputCheckBox = xInputCheckBox;
(globalThis as any).xInputFile = xInputFile;
(globalThis as any).xLi = xLi;
(globalThis as any).xSeparateur = xSeparateur;
(globalThis as any).enumEpaisseurSeparation = enumEpaisseurSeparation;
(globalThis as any).xTable = xTable;
(globalThis as any).xUl = xUl;
(globalThis as any).xInputTextAvecIcone = xInputTextAvecIcone;
(globalThis as any).xxArbre = xxArbre;
(globalThis as any).xxAssistantSaisieUtilisateur = xxAssistantSaisieUtilisateur;
(globalThis as any).xxAutoComplete = xxAutoComplete;
(globalThis as any).enumAutoCompleteTaille = enumAutoCompleteTaille;
(globalThis as any).xxBloqueEcran = xxBloqueEcran;
(globalThis as any).xxBoxer = xxBoxer;
(globalThis as any).enumBoxerMode = enumBoxerMode;
(globalThis as any).enumBoxerTaille = enumBoxerTaille;
(globalThis as any).enumPositionOrigine = enumPositionOrigine;
(globalThis as any).xxCarrousel = xxCarrousel;
(globalThis as any).xxCheckBox = xxCheckBox;
(globalThis as any).enumTypeCheckbox = enumTypeCheckbox;
(globalThis as any).xxChoixCouleur = xxChoixCouleur;
(globalThis as any).enumNuancierCouleurs = enumNuancierCouleurs;
(globalThis as any).xxChoixOuiNon = xxChoixOuiNon;
(globalThis as any).xxContainerEvent = xxContainerEvent;
(globalThis as any).xxDialog = xxDialog;
(globalThis as any).enumDialogTypeBouton = enumDialogTypeBouton;
(globalThis as any).enumTypeAlerte = enumTypeAlerte;
(globalThis as any).xxDockPanelDeprecated = xxDockPanelDeprecated;
(globalThis as any).DockPosition = DockPosition;
(globalThis as any).xxGrid = xxGrid;
(globalThis as any).xxGridItem = xxGridItem;
(globalThis as any).enumAlignementContenu = enumAlignementContenu;
(globalThis as any).xxIMC = xxIMC;
(globalThis as any).xxImageTabByte = xxImageTabByte;
(globalThis as any).enumTypeImage = enumTypeImage;
(globalThis as any).xxIndicateur = xxIndicateur;
(globalThis as any).EnumXxIndicateurNotifColor = EnumXxIndicateurNotifColor;
(globalThis as any).xxInputIntellisense = xxInputIntellisense;
(globalThis as any).xxInputNumerique = xxInputNumerique;
(globalThis as any).xxInputSpeech = xxInputSpeech;
(globalThis as any).xxInputUploadImage = xxInputUploadImage;
(globalThis as any).xxLecteurAudio = xxLecteurAudio;
(globalThis as any).xxLecteurCarteMagnetique = xxLecteurCarteMagnetique;
(globalThis as any).xxLinker = xxLinker;
(globalThis as any).xxListCheckBox = xxListCheckBox;
(globalThis as any).xxListChoix = xxListChoix;
(globalThis as any).xxListWrapper = xxListWrapper;
(globalThis as any).enumTypeTri = enumTypeTri;
(globalThis as any).xxListeDeroulante = xxListeDeroulante;
(globalThis as any).xxListeDeroulanteAutomatique = xxListeDeroulanteAutomatique;
(globalThis as any).xxListeDeroulanteSimpleNePlusUtiliser = xxListeDeroulanteSimpleNePlusUtiliser;
(globalThis as any).xxListeSelection = xxListeSelection;
(globalThis as any).xxListeChoixLang = xxListeChoixLang;
(globalThis as any).xxMenu = xxMenu;
(globalThis as any).xxNavOngletControl = xxNavOngletControl;
(globalThis as any).xxNavOngletItem = xxNavOngletItem;
(globalThis as any).xxPageWrapper = xxPageWrapper;
(globalThis as any).enumAlignementZone = enumAlignementZone;
(globalThis as any).xxPlanneur = xxPlanneur;
(globalThis as any).PlanneurRessource = PlanneurRessource;
(globalThis as any).PlanneurRDV = PlanneurRDV;
(globalThis as any).xxPlanneurColonne = xxPlanneurColonne;
(globalThis as any).xxPlanneurLigne = xxPlanneurLigne;
(globalThis as any).xxProgressBar = xxProgressBar;
(globalThis as any).xxQrCodeReader = xxQrCodeReader;
(globalThis as any).xxRadioButton = xxRadioButton;
(globalThis as any).itemRadioButton = itemRadioButton;
(globalThis as any).ETypeBouton = ETypeBouton;
(globalThis as any).xxRecorder = xxRecorder;
(globalThis as any).xxRouteContainer = xxRouteContainer;
(globalThis as any).xxSpecificationCreneaux = xxSpecificationCreneaux;
(globalThis as any).xxStackPanel = xxStackPanel;
(globalThis as any).xxTabControl = xxTabControl;
(globalThis as any).xxTabItem = xxTabItem;
(globalThis as any).xxTableauWrapper = xxTableauWrapper;
(globalThis as any).xxTexteEnrichi = xxTexteEnrichi;
(globalThis as any).xxToolTip = xxToolTip;
(globalThis as any).enumXxToolTipMode = enumXxToolTipMode;
(globalThis as any).enumXxToolTipPositionHeight = enumXxToolTipPositionHeight;
(globalThis as any).enumXxToolTipPositionWidth = enumXxToolTipPositionWidth;
(globalThis as any).xxTreeTabControl = xxTreeTabControl;
(globalThis as any).xxViewerPDF = xxViewerPDF;
(globalThis as any).xxVolet = xxVolet;
(globalThis as any).enumPositionVolet = enumPositionVolet;
(globalThis as any).xxWrapPanel = xxWrapPanel;
(globalThis as any).enumAlignementVerticalWrapPanel = enumAlignementVerticalWrapPanel;
(globalThis as any).enumAlignementHorizontalWrapPanel = enumAlignementHorizontalWrapPanel;
(globalThis as any).xxZoneModulable = xxZoneModulable;
(globalThis as any).EEtatZoneModulable = EEtatZoneModulable;
(globalThis as any).xxZoneRepliable = xxZoneRepliable;
(globalThis as any).enumXxZoneRepliableCouleurFleche = enumXxZoneRepliableCouleurFleche;
(globalThis as any).enumXxZoneRepliablePosition = enumXxZoneRepliablePosition;
(globalThis as any).xxZoom = xxZoom;
(globalThis as any).enumAffichageZoom = enumAffichageZoom;
(globalThis as any).enumTypeOrientation = enumTypeOrientation;
(globalThis as any).enumPosition = enumPosition;
(globalThis as any).xxPlanning = xxPlanning;
(globalThis as any).EPlanningTypeAffichage = EPlanningTypeAffichage;
(globalThis as any).PlanningRdv = PlanningRdv;
(globalThis as any).PlanningDisponibilite = PlanningDisponibilite;
(globalThis as any).enumTypeDispo = enumTypeDispo;
(globalThis as any).cacherxElements = cacherxElements;
(globalThis as any).afficherxElements = afficherxElements;
(globalThis as any).viderxElements = viderxElements;
(globalThis as any).assignerObjet = assignerObjet;
(globalThis as any).DateSerialisable = DateSerialisable;
(globalThis as any).HelperGeneric = HelperGeneric;
(globalThis as any).xOutils = xOutils;
(globalThis as any).EKeys = EKeys;
(globalThis as any).ETypeAlertify = ETypeAlertify;
(globalThis as any).xElementHolder = xElementHolder;
(globalThis as any).xMaths = xMaths;
(globalThis as any).xTime = xTime;
(globalThis as any).BindableObject = BindableObject;
(globalThis as any).xStyle = xStyle;
(globalThis as any).Container = Container;
(globalThis as any).enumComportementBouton = enumComportementBouton;
(globalThis as any).xxToolTipBouton = xxToolTipBouton;
(globalThis as any).PlanningRdv = PlanningRdv;
(globalThis as any).PlanningDisponibilite = PlanningDisponibilite;
(globalThis as any).PlanningRessource = PlanningRessource;
(globalThis as any).enumTypeDispo = enumTypeDispo;
